### ISSUE TITLE
Can run unit tests.

### ISSUE THREAD

**Issue by joerozek** [JoeRoddy/firebase-sql#1]
I'm trying  look into to issues for firestore but I can't run unit tests  

1. dates in where clauses don't seem to work in firestation
2. sub collection queries doesn't seem to work.  `select * from users.subcollection`

Try to run jest tests.  `npm test` and getting the following error for all firestore tests.

```
Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.

      at mapper (node_modules/jest-jasmine2/build/queueRunner.js:25:45)
```

**Comment by JoeRoddy** [comment]
Sorry for the delay, just noticed this issue @joerozek .  I'm looking into it now. Admittedly, the tests can be pretty finicky.

**Comment by JoeRoddy** [comment]
So, (giant meme incoming), it's working on my machine. 

Did you add your db config to [this file](https://github.com/JoeRoddy/firebase-sql/blob/master/src/query_runners/test_resources/db_config.js)?

For me, it ends up looking something like:


```
     export default {

       databaseURL: "https://fbsql-tests.firebaseio.com",

        serviceAccount: {

         type: "service_account",

         project_id: "fbsql-tests",

        private_key_id: "keyid",

       private_key:

       "-----BEGIN PRIVATE KEY-----\nsupersecretkey\n-----END PRIVATE KEY-----\n",

       client_email: "firebase-adminsdk-...@.....iam.gserviceaccount.com",

       client_id: "1000............",

       auth_uri: "https://accounts.google.com/o/oauth2/auth",

       token_uri: "https://oauth2.googleapis.com/token",

       auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs",

       client_x509_cert_url:

        "https://www.googleapis.com...."

       }
    };

```

**Comment by JoeRoddy** [comment]
You might also need to manually enable cloud firestore for that database in the firebase console.

**Comment by JoeRoddy** [comment]
I'm going to close this, but feel free to reopen if you're unable to get them running @joerozek  .  I'm sure we can figure it out.
